version: '3.3'

services:
   postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - /home/data/postgresql/data:/var/lib/postgresql/data
networks:
  default:
    name: thoothuvan
    external: true
